### PR TITLE
Terraform aws odc v1.8

### PR DESCRIPTION
**Pull request by woodcockr**
# Why this change is needed
> Describe why this change is needed, what issues it will fix and the benefits the change will add

This PR is for release  v1.8 of the datacube-k8s-eks terraform aws infrastructure as code.
***This is a MAJOR refactor and is not suitable for in-place update of an existing deployment using previous versions***
Fortunately you can do a test deployment right alongside your existing one so long as you take care to set your configuration to avoid collisions in domain names, cluster name, etc. I won't explain how, if you don't know how to do this you shouldn't be operating terraform ;-)

# Negative effects of this change
> Will making this change break or change an existing functionality? flag it here

This is a new release with a new approach. Indeed this repo is now a terraform module repository with an example of a live repo in it. You can look at that to see how you would start with your own live repo using this module repo.

### CODE REVIEW

**Comment by woodcockr** [comment]
If you are wondering why v1.8 and what happened to other versions? 
The devs decided to align the release version with upcoming v1.8 release of datacube-core.

**Comment by NikitaGandhi** [comment]
> Why remove?

`cluster_id` parameter in cognito module is only used for tags. To bring consistency as other modules, default tags are only `owner`, `namespace`, `environment`. To have additional tags, we added `tags` parameter. So it is safe remove. 

See README: https://github.com/opendatacube/datacube-k8s-eks/tree/terraform-aws-odc/cognito

**Comment by woodcockr** [comment]
This is now ready for review for release as at tag v1.8.0-rc.2

**Comment by woodcockr** [comment]
I've checked the last few commits and as expected there are no infrastructure changes - just docs and merge conflict resolution (thank you for that @NikitaGandhi ).

This is good to go as soon as one of you complete Review @tom-butler @NikitaGandhi 
Squash and Merge and tag master as v1.8.0 cause we are awesome!!!

**Pull request merged**
