### PR TITLE
Add variable for EKS cluster logging settings

### PR DESCRIPTION
**Pull request by umeat**
This adds support for enabling EKS control plane logging into CloudWatch.

Example:
```
module ... {
  enabled_cluster_log_types = ["api", "audit"]
...
```

Full list of log types here: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

### CODE REVIEW

**Comment by jmettes** [comment]
The terraform documentation mentions using `depends_on` to prevent ordering issues. Is that needed here?
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#enabling-control-plane-logging

**Comment by umeat** [comment]
Good catch. In my testing, I left it up to AWS to automatically create the log group, but I agree it's better to create it manually and use some default retention period.

I'll modify the PR and follow the example they use there. Note that if you've ever manually setup the logging then you'll either need to import the automatically created log group into terraform state, or just delete the log groups.

**Comment by NikitaGandhi** [comment]
Can you please make this an optional setup to enable EKS logging. 

There are few things to consider otherwise it will breaks deployment:
- Needed a bool variable - `enable_eks_logging` - to manage(enable or disable) the EKS logging. Set defaults with false. This will allow this feature to release without impacting others.
- Define variables with default if possible. 
- Also haven't seen use of `log_retention_period` - I guess you are planning to create a `aws_cloudwatch_log_group` resource  for EKS logging explicitly. If so, make it optional based on  `enable_eks_logging`.
- Update document

**Comment by umeat** [comment]
Regarding `enable_eks_logging`, the `enabled_cluster_log_types` attribute of resource.aws_eks_cluster default is an empty list - so the only thing this flag would do is allow you to conditionally create the Cloudwatch log group. Which I don't see as necessary. If you think it's required, we could have it created if the length of the `enabled_cluster_log_types` list is > 0.

I'll make the default for `enabled_cluster_log_types` and empty list. Thanks.

You're right about the log retention period - I mistakenly didn't commit the log group resource.

Happy to update the document as well.

Summary: In my opinion (once I make the above mentioned changes), the question of whether to add an `enable_eks_logging` flag hinges on whether you think it's necessary to not create the cloudwatch log group. I think it is not, and note that if you temporarily disable logging for whatever reason - then terraform will try to delete the log group, which I think is not ideal.

**Comment by umeat** [comment]
Added documentation, added cloudwatch group tf file, added default for `enabled_cluster_log_types`.

Thoughts on whether an independent enable flag is required?

**Review by NikitaGandhi — APPROVED** [review]

**Review by woodcockr — CHANGES_REQUESTED** [review]
> Summary: In my opinion (once I make the above mentioned changes), the question of whether to add an enable_eks_logging flag hinges on whether you think it's necessary to not create the cloudwatch log group. I think it is not, and note that if you temporarily disable logging for whatever reason - then terraform will try to delete the log group, which I think is not ideal.

I agree with @NikitaGandhi. The creation of the cloudwatch log group should be conditional on whether or not logging is enabled. The creation of a resource that is not in use is problematic when auditing infrastructure and tends to create unnecessary quests to determine whether or not something is required during account audits and later code refactors. Having this explicitly be part of enabling logging eliminates later ambiguity.

The concern about temporarily disabling logging is also valid, but the flag to enable the logging resources doesn't so far as I can tell need to be the same flag to enable/disable logging because there is already control over what is logged - if `enabled_cluster_log_types = []` there is no reason why it would delete the cloudwatch logs that I can see.

**Comment by umeat** [comment]
When temporarily disabling, you would need to know not to set `enable_eks_logging` to false. Because you would use that attribute to conditionally create the cloudwatch log group, if you set it to false then the log group will be deleted by terraform.

I agree if you set `enabled_cluster_log_types = []` then that'll work - but in combination with a separate `enable_eks_logging` attribute I believe it'll just lead to confusion.

**Comment by woodcockr** [comment]
> When temporarily disabling, you would need to know not to set `enable_eks_logging` to false. Because you would use that attribute to conditionally create the cloudwatch log group, if you set it to false then the log group will be deleted by terraform.
> 
> I agree if you set `enabled_cluster_log_types = []` then that'll work - but in combination with a separate `enable_eks_logging` attribute I believe it'll just lead to confusion.

I don't think (with docs) that will be anywhere near as confusing as auditing a AWS account and finding an unexpected bucket that may or may not be in use.

I'm really not keen on having the bucket exist if I'm not enabling eks logging.

**Comment by umeat** [comment]
No buckets are created. Just a CloudWatch log group.

**Comment by woodcockr** [comment]
> No buckets are created. Just a CloudWatch log group.

opps, wrong term on my part - meant Cloud Watch Log group.

Account audits here are common - if it ain't in use (in this case enabled), don't create it.

**Comment by umeat** [comment]
In that case, I might suggest calling the bool `enable_cluster_log_group` instead. This way it doesn't sound like setting it to false will stop the logging, and you can still choose to only set `enabled_cluster_log_types` and let AWS create the log group if you want.

And also maybe change `log_retention_period` to `cluster_log_retention_period` so the names look more aligned.

So overall it would look like:

```
enable_cluster_log_group = true
enabled_cluster_log_types = ["api", "audit"]
```
to temporarily disable:
```
enable_cluster_log_group = true
enabled_cluster_log_types = []
```

or if you want to let AWS create the log group automatically:
```
enable_cluster_log_group = false
enabled_cluster_log_types = ["api", "audit"]
```

This is still a bit confusing imo - in that if you ever set `enable_cluster_log_group` from true to false (and don't unset the `enabled_cluster_log_types`), thinking it will stop the logging, you'll actually just delete the log group and all the existing logs with it. Even worse, AWS will recreate the log group again automatically.

I can't see that finding an empty cloudwatch log group called `/aws/eks/${var.cluster_name}/cluster` in an account that contains an EKS cluster of the same name is going to stress anyone out (why shouldn't the cluster be automatically created with an associated cloudwatch log group?). But if you're happy with the above approach, I can give it a go.

**Comment by woodcockr** [comment]
> or if you want to let AWS create the log group automatically:
> 
> ```
> enable_cluster_log_group = false
> enabled_cluster_log_types = ["api", "audit"]
> ```
> 
> This is still a bit confusing imo - in that if you ever set `enable_cluster_log_group` from true to false (and don't unset the `enabled_cluster_log_types`), thinking it will stop the logging, you'll actually just delete the log group and all the existing logs with it. Even worse, AWS will recreate the log group again automatically.
> 

Perhaps enable_custom_cluster_log_group ? Though it would be nice to disable the AWS automated creation of a log group and have it error instead.

> I can't see that finding an empty cloudwatch log group called `/aws/eks/${var.cluster_name}/cluster` in an account that contains an EKS cluster of the same name is going to stress anyone out (why shouldn't the cluster be created with an associated cloudwatch log group already made?). But if you're happy with the above approach, I can give it a go.

All depends on where you are coming from, and level of paranoia, and ....
I like the proposed solution and think it is clear enough.

**Comment by stacyhorton** [comment]
I had created a PR to add this functionality without noticing this one was already in progress.  It reads as if we had concensus on the way forward, can I assist @umeat ?

**Comment by umeat** [comment]
@stacyhorton Please. I have had no time to finish this off.

**Comment by stacyhorton** [comment]
Hi @NikitaGandhi and @woodcockr , I think I have made the changes requested in the various comments but let me know if I missed anything:

- Updated README
- Added enable_custom_cluster_log_group variable
- Made creation of Log Group conditional based on enable_custom_cluster_log_group

I also re-tested the combinations of variables to make sure everything works as expected. If nothing is supplied, there are no changes in the `terraform plan`.

**Comment by stacyhorton** [comment]
Hi @woodcockr , sorry to hassle but I believe I've addressed your change requests. Would you have some time to verify and approve?  Thanks

**Review by woodcockr — APPROVED** [review]

**Comment by woodcockr** [comment]
> Hi @woodcockr , sorry to hassle but I believe I've addressed your change requests. Would you have some time to verify and approve? Thanks

I was on leave but all looks good.

**Pull request merged**
